

USE [master]
GO

CREATE DATABASE [db-events]
GO

ALTER DATABASE [db-events] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db-events].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [db-events] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db-events] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db-events] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db-events] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db-events] SET ARITHABORT OFF 
GO
ALTER DATABASE [db-events] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [db-events] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db-events] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db-events] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db-events] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db-events] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db-events] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db-events] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db-events] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db-events] SET  ENABLE_BROKER 
GO
ALTER DATABASE [db-events] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db-events] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db-events] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [db-events] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [db-events] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db-events] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [db-events] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [db-events] SET RECOVERY FULL 
GO
ALTER DATABASE [db-events] SET  MULTI_USER 
GO
ALTER DATABASE [db-events] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db-events] SET DB_CHAINING OFF 
GO
ALTER DATABASE [db-events] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [db-events] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db-events] SET DELAYED_DURABILITY = DISABLED 
GO
-- ALTER DATABASE [db-events] SET ACCELERATED_DATABASE_RECOVERY = OFF  
-- GO
-- EXEC sys.sp_db_vardecimal_storage_format N'db-events', N'ON'
-- GO
-- ALTER DATABASE [db-events] SET QUERY_STORE = OFF
-- GO
USE [db-events]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Events](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Pais] [nvarchar](max) NULL,
	[Regiao] [nvarchar](max) NULL,
	[Sensor] [nvarchar](max) NULL,
	[Valor] [nvarchar](max) NULL,
	[Timestamp] [nvarchar](max) NULL,
	[Status] [nvarchar](max) NULL,
	[Created] [datetime2](7) NOT NULL,
	[Updated] [datetime2](7) NULL,
 CONSTRAINT [PK_Events] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
-- USE [master]
-- GO
ALTER DATABASE [db-events] SET  READ_WRITE 
GO

CREATE LOGIN [rabbit] WITH PASSWORD = 'Rabbit123!'
GO

CREATE USER [rabbit] FOR LOGIN [rabbit] WITH DEFAULT_SCHEMA=[dbo]
GO

GRANT ALL ON __EFMigrationsHistory TO [rabbit];
GRANT ALL ON Events TO [rabbit];
GO